### ISSUE TITLE
Continuous rotation as  servo

### ISSUE THREAD

**Issue by sriranjanr** [RhobanProject/Dynaban#1]
Hello,

I think it would be a good feature to implement a continuous rotation servo like being able to move it as a servo but for more than a single revolution or 360. Say if we command it to rotate by 750 degress it should rotate two turn and then the extra 30deg as well. Is it possible to implement this feature?

**Comment by Gregwar** [comment]
Hello @sriranjanr 
Thanks for opening this repo first issue
Did you give a try to the firmware on one of your servos?
ping @LK

**Comment by sriranjanr** [comment]
I am planning to buy the MX64 servos.Prior to coming across your firmware I though I would switch the servo to wheel more when it reaches 360deg and then after some minute rotation like say 0.088 deg I will change it to servo mode again but I am not sure if this fix will work.So I asked whether it is possible to use your firmware to make the dynamixel work like a "continuous rotation servo".

**Comment by RemiFabre** [comment]
Hi there,

What you're willing to do is easy with the Dynaban firmware. 
The servo will always try to go to the goal position through the shortest path, unless an angle limit makes it impossible. In wheel mode there is no more angle limits so you can always ask a goal position further away.

To put the servo in wheel mode, just set bot CW and CCW angle limits to 0.
Then, ask a goal position that is always further away, modulo 4096, for example : 

1) 1024, then 2048, then 3072, then 0, then 1024, then 2048 will make the servo do 1,5 turns.
2) Or, a smoother way. Update frequently your goal_position as follows : goal_position = present_position + 1500 (or -1500)

Also, it will be possible to write 750 degrees and let the servo handle it. It's the "multi-turn feature" that will be release very soon (either today or next week).

**Comment by sriranjanr** [comment]
OK I will wait for the release.

**Comment by RemiFabre** [comment]
Hi,

The multi-turn feature is now available on the Dynaban firmware.

To activate it, just set the CW and CCW angle limits to 4095. In that mode, the goal position ranges from -32768 to +32768.

**Comment by sriranjanr** [comment]
Thanks a lot but I am not going with these servos because as I read they cannot deliver 90% continuous torque.

**Comment by RemiFabre** [comment]
What do you mean by "they cannot deliver 90% continuous torque" ? Do you have a link to that information?
If the Dynamixel firmware has such a limitation, that's not the case with Dynaban.

Anyway, good luck with your project
