### ISSUE TITLE
Compatibility with MX-28

### ISSUE THREAD

**Issue by toshiharutf** [RhobanProject/Dynaban#3]
Hello,
Do you know perhaps if your firmware will also be compatible with the MX-28 servo?
Thanks

**Comment by Gregwar** [comment]
Hello,
Unfortunately, we don't plan to work further on this project
I think porting this on MX-28 is feasible (I think it is the same microcontroller), but reverse engineering can be surprising sometime

**Comment by toshiharutf** [comment]
Hello,
No issues there, I will try it by myself. Just wanted to know how feasible it was.
From the documentation, I get you are using the default robotis's bootloader, right? Or do I need to wire an st-link debugger?

**Comment by Gregwar** [comment]
Yes, we have a Python script that does that, reffered here:

https://github.com/RhobanProject/Dynaban/blob/master/firmware/Makefile#L122

**Comment by toshiharutf** [comment]
Great. Thank you for the info!
